<div class="fb-like-box"
     data-href="https://www.facebook.com/gdevche"
     data-width="225"
     data-height="246"
     data-colorscheme="light"
     data-show-faces="true"
     data-header="true"
     data-stream="false"
     data-show-border="true"></div>